### ISSUE TITLE
Errors in installation (build on windows with -lm)

### ISSUE THREAD

**Issue by ichxw** [whitead/molbloom#8]
Hello, Andrew
Below are some errors I got when trying to install molbloom on Windows 10. Did I have wrong version of compiler? Thanks.
 
000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" /Tcmolbloom/bloom.c /Fobuild\temp.win-amd64-cpython-38\Release\molbloom/bloom.obj
  bloom.c
  C:\Users\User\AppData\Local\Temp\pip-req-build-qs_adk9b\molbloom\bloom/bloom.h(68): warning C4477: 'printf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 2 has type 'uint64_t'
  C:\Users\User\AppData\Local\Temp\pip-req-build-qs_adk9b\molbloom\bloom/bloom.h(68): note: consider using '%llu' in the format string
  C:\Users\User\AppData\Local\Temp\pip-req-build-qs_adk9b\molbloom\bloom/bloom.h(68): note: consider using '%Iu' in the format string
  C:\Users\User\AppData\Local\Temp\pip-req-build-qs_adk9b\molbloom\bloom/bloom.h(68): note: consider using '%I64u' in the format string
  C:\Users\User\AppData\Local\Temp\pip-req-build-qs_adk9b\molbloom\bloom/bloom.h(68): warning C4477: 'printf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 4 has type 'uint64_t'
  C:\Users\User\AppData\Local\Temp\pip-req-build-qs_adk9b\molbloom\bloom/bloom.h(68): note: consider using '%llu' in the format string
  C:\Users\User\AppData\Local\Temp\pip-req-build-qs_adk9b\molbloom\bloom/bloom.h(68): note: consider using '%Iu' in the format string
  C:\Users\User\AppData\Local\Temp\pip-req-build-qs_adk9b\molbloom\bloom/bloom.h(68): note: consider using '%I64u' in the format string
  C:\Users\User\AppData\Local\Temp\pip-req-build-qs_adk9b\molbloom\bloom/bloom.h(158): warning C4477: 'printf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 2 has type 'uint64_t'
  C:\Users\User\AppData\Local\Temp\pip-req-build-qs_adk9b\molbloom\bloom/bloom.h(158): note: consider using '%llu' in the format string
  C:\Users\User\AppData\Local\Temp\pip-req-build-qs_adk9b\molbloom\bloom/bloom.h(158): note: consider using '%Iu' in the format string
  C:\Users\User\AppData\Local\Temp\pip-req-build-qs_adk9b\molbloom\bloom/bloom.h(158): note: consider using '%I64u' in the format string

**Comment by whitead** [comment]
Those all look like notes or warnings. Could you check further to see if there is a line with `error` in it?

**Comment by ichxw** [comment]
> Those all look like notes or warnings. Could you check further to see if there is a line with `error` in it?

Thanks for your quick response. Below is the error message. 
```
  Traceback (most recent call last):
    File "C:\Users\User\.conda\envs\my-rdkit-env\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 349, in <module>
      main()
    File "C:\Users\User\.conda\envs\my-rdkit-env\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\User\.conda\envs\my-rdkit-env\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 248, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\build_meta.py", line 413, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\build_meta.py", line 398, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\build_meta.py", line 484, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 13, in <module>
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\__init__.py", line 108, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
      return run_commands(dist)
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
      dist.run_commands()
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\dist.py", line 1221, in run_command
      super().run_command(command)
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 325, in run
      self.run_command("build")
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\dist.py", line 1221, in run_command
      super().run_command(command)
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
      self.run_command(cmd_name)
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\dist.py", line 1221, in run_command
      super().run_command(command)
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run
      _build_ext.run(self)
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
      self.build_extensions()
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
      self._build_extensions_serial()
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
      _build_ext.build_extension(self, ext)
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 572, in build_extension
      self.compiler.link_shared_object(
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\_distutils\ccompiler.py", line 752, in link_shared_object
      self.link(
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 473, in link
      lib_opts = gen_lib_options(self, library_dirs, runtime_library_dirs, libraries)
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-a3265qs8\overlay\Lib\site-packages\setuptools\_distutils\ccompiler.py", line 1243, in gen_lib_options
      (lib_dir, lib_name) = os.path.split(lib)
    File "C:\Users\User\.conda\envs\my-rdkit-env\lib\ntpath.py", line 185, in split
      p = os.fspath(p)
  TypeError: expected str, bytes or os.PathLike object, not NoneType
  ----------------------------------------
  ERROR: Failed building wheel for molbloom
Failed to build molbloom
ERROR: Could not build wheels for molbloom which use PEP 517 and cannot be installed directly
```
BTW. It works well on Ubuntu.

**Comment by ichxw** [comment]
Thanks for looking into this. Glad it works great on Linux.

**Comment by yonmina97** [comment]
Has the package issue been resolved in Windows?
The same problem occurs with virtual env > conda > pip install chemcrow > molbloom install > Exception Error

**Comment by SamCox822** [comment]
This seems related here - I also get the error `ERROR: Failed building wheel for molbloom` on my Mac, in a conda env. I found that mol bloom currently doesn't work nicely with python3.12 and using older versions (3.11) worked for me.

**Comment by whitead** [comment]
Windows and py3.12 are present in latest release
